// data/movies.js
export const movies = [
  {
    MovieID: 1,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 2,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 3,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 4,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 5,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 6,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  }, {
    MovieID: 7,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  {
    MovieID: 8,
    MovieNameVietnamese: "Naruto (Phần 1)",
    MovieNameEnglish: "Naruto (Season 1)",
    MovieStatus: "New",
    ReleaseYear: 2002,
    AgeRestriction: "T13",
    NumberOfEpisodes: "52 tập",
    Country: "Nhật Bản",
    SummaryTitle: "Bạo lực, chất gây nghiện...",
    SummaryContent: "12 năm trước, Cửu Vĩ Kurama tấn công làng Lá...",
    Actor: "Junko Takeuchi, Noriaki Sugiyama...",
    Director: "Masashi Kishimoto",
    MovieGenre: "Hoạt hình, Hành động, Phiêu lưu",
    MovieImagePath: "https://images.fptplay53.net/media/OTT/VOD/2023/12/06/naruto-phan-1-fpt-play-1701854677638_Landscape.jpg",
    SlugMovieName: "naruto-phan-1"
  },
  // ... thêm phim khác tương tự
];
